part of './app_text.dart';

class _SmallAppText extends AppText {
  const _SmallAppText(
    String text, {
    Key? key,
    Color? color,
    String? family,
    double? size,
    FontWeight? weight,
    TextAlign? align,
    TextDecoration? decoration,
    Color? backgroundColor,
    double? height,
    FontStyle? fontStyle,
    int? maxLines,
    TextOverflow? overflow,
    bool? softWrap,
    double? letterSpacing,
    TextBaseline? textBaseline,
    void Function()? onTap,
    EdgeInsetsGeometry? padding,
    TextDecorationStyle? decorationStyle,
    Color? decorationColor,
  }) : super(
          text,
          key: key,
          color: color,
          family: family,
          size: size,
          weight: weight,
          align: align,
          decoration: decoration,
          backgroundColor: backgroundColor,
          height: height,
          fontStyle: fontStyle,
          maxLines: maxLines,
          overflow: overflow,
          softWrap: softWrap,
          letterSpacing: letterSpacing,
          textBaseline: textBaseline,
          onTap: onTap,
          padding: padding,
          decorationStyle: decorationStyle,
          decorationColor: decorationColor,
        );
}

class MediumAppText extends AppText {
  const MediumAppText(
    String text, {
    Key? key,
    Color? color,
    String? family,
    double? size,
    FontWeight? weight,
    TextAlign? align,
    TextDecoration? decoration,
    Color? backgroundColor,
    double? height,
    FontStyle? fontStyle,
    int? maxLines,
    TextOverflow? overflow,
    bool? softWrap,
    double? letterSpacing,
    TextBaseline? textBaseline,
    void Function()? onTap,
    EdgeInsetsGeometry? padding,
    TextDecorationStyle? decorationStyle,
    Color? decorationColor,
  }) : super(
          text,
          key: key,
          color: color,
          family: family,
          size: size,
          weight: weight,
          align: align,
          decoration: decoration,
          backgroundColor: backgroundColor,
          height: height,
          fontStyle: fontStyle,
          maxLines: maxLines,
          overflow: overflow,
          softWrap: softWrap,
          letterSpacing: letterSpacing,
          textBaseline: textBaseline,
          onTap: onTap,
          padding: padding,
          decorationStyle: decorationStyle,
          decorationColor: decorationColor,
        );
}

class LargeAppText extends AppText {
  const LargeAppText(
    String text, {
    Key? key,
    Color? color,
    String? family,
    double? size,
    FontWeight? weight,
    TextAlign? align,
    TextDecoration? decoration,
    Color? backgroundColor,
    double? height,
    FontStyle? fontStyle,
    int? maxLines,
    TextOverflow? overflow,
    bool? softWrap,
    double? letterSpacing,
    TextBaseline? textBaseline,
    void Function()? onTap,
    EdgeInsetsGeometry? padding,
    TextDecorationStyle? decorationStyle,
    Color? decorationColor,
  }) : super(
          text,
          key: key,
          color: color,
          family: family,
          size: size,
          weight: weight,
          align: align,
          decoration: decoration,
          backgroundColor: backgroundColor,
          height: height,
          fontStyle: fontStyle,
          maxLines: maxLines,
          overflow: overflow,
          softWrap: softWrap,
          letterSpacing: letterSpacing,
          textBaseline: textBaseline,
          onTap: onTap,
          padding: padding,
          decorationStyle: decorationStyle,
          decorationColor: decorationColor,
        );
}
